### ISSUE TITLE
QA_Instrumentation and working principles of solutions infra red spectroscopy_Experiment_Fixed-Mirror-&-Movable-Mirror-needs-to-be-added

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/physical-chemistry-responsive-lab#20]
Defect Description :
In the experiment section of "Instrumentation and working principles of solutions infra red spectroscopy" experiment, Fixed & Movable Mirrors are not included/not clearly visible in the converted experiment. Where as in the original experiment the Fixed & the Movable Mirrors are is provided.

Actual Result :
In the experiment section of "Instrumentation and working principles of solutions infra red spectroscopy" experiment, Fixed & Movable Mirrors are not included/not clearly visible in the converted experiment. Where as in the original experiment the Fixed & the Movable Mirrors are is provided. Refer the attachment for the details.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
**In the screen shot left side image is from the original experiment that has the Fixed & the Movable Mirrors**
![qa_pc_i21](https://user-images.githubusercontent.com/13479177/28006484-20b0beb4-656d-11e7-899e-7a5590861d87.png)

**Comment by kalpit4088** [comment]
Issue Resolved

**Comment by BSravanthi** [comment]
Closed #20
