### ISSUE TITLE
QA_Instrumentation and working principles of solutions infra red spectroscopy_Experiment_Beam-Splitter-is-not-included

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/physical-chemistry-responsive-lab#21]
Defect Description :
In the experiment section of "Instrumentation and working principles of solutions infra red spectroscopy" experiment, Beam Splitter is not included in the converted experiment. Where as in the original experiment the Beam Splitter is provided.

Actual Result :
In the experiment section of "Instrumentation and working principles of solutions infra red spectroscopy" experiment, Beam Splitter is not included in the converted experiment. Where as in the original experiment the Beam Splitter is provided. Refer the attachment for the details.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
**In the screen shot right side image is from the original experiment that has Beam Splitter**
![qa_pc_i23](https://user-images.githubusercontent.com/13479177/28012834-b7d3fd76-6584-11e7-86e2-930a0a0a1113.png)

**Comment by kalpit4088** [comment]
Ma'am there is no screenshot. please attach that screenshot!

**Comment by BSravanthi** [comment]
@kalpit4088 please check the screen shot.

**Comment by kalpit4088** [comment]
Issue Resolved

**Comment by BSravanthi** [comment]
Closed #21
